AzureKeyVaultManager/AzureKeyVaultManager.Web/Models/KeyVault.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AzureKeyVaultManager.Web.Models
{
    public class KeyVault
    {
        [DisplayName("Vault URL")]
        [Required]
        [DataType(DataType.Url)]
        public string VaultURl { get; set; }
        
        [DisplayName("Client App ID")]
        [Required]
        [DataType(DataType.Text)]
        public string ClientAppId { get; set; }
        
        [DisplayName("Client App Secret")]
        [Required]
        [DataType(DataType.Text)]
        public string ClientAppSecretKey { get; set; }
    }
}

AzureKeyVaultManager/AzureKeyVaultManager.Web/Models/KeyVaultKey.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace AzureKeyVaultManager.Web.Models
{
    public class KeyVaultKey
    {
        [DisplayName("Key Name")]
        public string Name { get; set; }
        [DisplayName("Created On")]
        public string CreatedOn { get; set; }
        [DisplayName("Expires On")]
        public string ExpiresOn { get; set; }
    }
}

AzureKeyVaultManager/AzureKeyVaultManager.Web/Models/KeyVaultSecret.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AzureKeyVaultManager.Web.Models
{
    public class KeyVaultSecret
    {
        public string SecretId { get; set; }

        [Required]
        [DisplayName("Secret Name")]
        public string Name { get; set; }

        [DisplayName("Created On")]
        public string CreatedOn { get; set; }

        [DisplayName("Expires On")]
        public string ExpiresOn { get; set; }
        public string Version { get; set; }

        [Required]
        [DisplayName("Secret Value")]
        public string SecretValue { get; set; }
    }
}

AzureKeyVaultManager/AzureKeyVaultManager.Web/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AzureKeyVaultManager.Web.Controllers
{
    public class CommentsController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

AzureKeyVaultManager/AzureKeyVaultManager.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AzureKeyVaultManager.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AzureKeyVaultManager/AzureKeyVaultManager.Web/Controllers/KeyVaultController.cs
using AzureKeyVaultManager.Web.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AzureKeyVaultManager.Web.Controllers
{
    public class KeyVaultController : Controller
    {
        public ActionResult Index(FormCollection collection)
        {
            if (collection.Keys.Count == 4)
            {
                try
                {
                    Session["vaulturl"] = collection["VaultURl"];
                    Session["appid"] = collection["ClientAppId"];
                    Session["appsecret"] = collection["ClientAppSecretKey"];

                    return RedirectToAction("Menu");
                }
                catch
                {
                    return View();
                }
            }
            else
            {
                return View();
            }
        }

        public ActionResult Menu()
        {
            return View();
        }

        #region Secrets

        public ActionResult Secrets()
        {
            try
            {
                var service = CreateVaultService();
                var collection = service.GetSecrets();
                return View(collection);
            }
            catch(Exception ex)
            {
                ViewBag.Exception = ex.Message;
                ViewBag.InnerException = ex.InnerException == null ? String.Empty : ex.InnerException.Message;
                return View("Error");
            }
        }

        public ActionResult SecretDetails(string secretName)
        {
            try
            {
                var service = CreateVaultService();
                var collection = service.GetVersionsOfSecret(secretName);
                return View(collection);
            }
            catch (Exception ex)
            {
                ViewBag.Exception = ex.Message;
                ViewBag.InnerException = ex.InnerException == null ? String.Empty : ex.InnerException.Message;
                return View("Error");
            }
        }

        public ActionResult CreateSecret(FormCollection collection)
        {
            try
            {
                if (collection.Keys.Count > 2)
                {
                    var service = CreateVaultService();
                    var name = collection["SecretName"];
                    var value = collection["SecretValue"];
                    var secret = service.CreateSecret(name, value);
                }
                return View();
            }
            catch (Exception ex)
            {
                ViewBag.Exception = ex.Message;
                ViewBag.InnerException = ex.InnerException == null ? String.Empty : ex.InnerException.Message;
                return View("Error");
            }
        }

        public ActionResult DeleteSecret(string secretName)
        {
            try
            {
                var service = CreateVaultService();
                service.DeleteSecret(secretName);
                return RedirectToAction("Secrets");
            }
            catch (Exception ex)
            {
                ViewBag.Exception = ex.Message;
                ViewBag.InnerException = ex.InnerException == null ? String.Empty : ex.InnerException.Message;
                return View("Error");
            }
        }

        #endregion

        #region Keys

        public ActionResult Keys()
        {
            try
            {
                var service = CreateVaultService();
                var colection = service.GetKeys();
                return View(colection);
            }
            catch (Exception ex)
            {
                ViewBag.Exception = ex.Message;
                ViewBag.InnerException = ex.InnerException == null ? String.Empty : ex.InnerException.Message;
                return View("Error");
            }
        }

        #endregion

        private KeyVaultService CreateVaultService()
        {
            string url = Session["vaulturl"].ToString();
            string appId = Session["appid"].ToString();
            string appSecret = Session["appsecret"].ToString();

            return new KeyVaultService(url, appId, appSecret);
        }
    }
}

AzureKeyVaultManager/AzureKeyVaultManager.Web/Views/Comments/Index.cshtml
@{
    ViewBag.Title = "Comments";
}

<div class="fb-comments" data-href="http://keyvaultmanager.azurewebsites.net/" data-numposts="10"></div>

AzureKeyVaultManager/AzureKeyVaultManager.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Azure Key Vault Manager";
}

<div class="jumbotron">
    <h2>Azure Key Vault Manager V 1.0.2</h2>
    <p class="lead">Are you looking for a tool to manage your Azure Key Vault ?</p>
    <p class="btn">@Html.ActionLink("Start", "Index", "KeyVault")</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h3>Azure Key Vault links</h3>
        <p><a href="http://azure.microsoft.com/en-us/services/key-vault/" target="_blank">Azure Key Vault &raquo;</a></p>
        <p><a href="http://azure.microsoft.com/en-us/documentation/services/key-vault/" target="_blank">Documentation &raquo;</a></p>
        <p><a href="http://azure.microsoft.com/en-us/pricing/details/key-vault/" target="_blank">Pricing &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h3>Other Links</h3>
        <p><a href="https://thuruinhttp.wordpress.com" target="_blank">Blog &raquo;</a></p>
        <p><a href="https://github.com/thuru/AzureKeyVaultManager" target="_blank">Source Code &raquo;</a></p>
        <p><a href="https://thuruinhttp.wordpress.com/2015/05/30/azure-key-vault-setup-and-usage-scenarios/" target="_blank">Key Vault Explained &raquo;</a></p>
        <p><a href="https://github.com/thuru/AzureKeyVaultSample/tree/master/AzureKeyVaultSample/PowerShellScript" target="_blank">Key Vault PowerShell &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <p><div class="fb-share-button" data-href="http://keyvaultmanager.azurewebsites.net/" data-layout="button_count"></div></p>
        <p><div class="fb-like" data-href="http://keyvaultmanager.azurewebsites.net/" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div></p>

    </div>
</div>

AzureKeyVaultManager/AzureKeyVaultManager.Web/Views/KeyVault/CreateSecret.cshtml
@model AzureKeyVaultManager.Web.Models.KeyVaultSecret

@{
    ViewBag.Title = "CreateSecret";
}

<h2>Create Secret</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.SecretName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SecretName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SecretName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SecretValue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SecretValue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SecretValue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Menu", "Menu")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AzureKeyVaultManager/AzureKeyVaultManager.Web/Views/KeyVault/Index.cshtml
@model AzureKeyVaultManager.Web.Models.KeyVault

@{
    ViewBag.Title = "Key Vault";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h2>This site <strong>DOES NOT</strong>store any information.</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.VaultURl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VaultURl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VaultURl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientAppId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClientAppId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClientAppId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientAppSecretKey, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClientAppSecretKey, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClientAppSecretKey, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Load Details to Session" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AzureKeyVaultManager/AzureKeyVaultManager.Web/Views/KeyVault/Keys.cshtml
@model IEnumerable<AzureKeyVaultManager.Web.Models.KeyVaultKey>

@{
    ViewBag.Title = "Keys";
}

<h3>Keys</h3>
<h4>Vault : @Session["vaulturl"].ToString().ToLower() has @Model.Count() of key(s).</h4>

<table class="table">
    <tr>
        <th>
           
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExpiresOn)
        </th>
        <th></th>
    </tr>

@for (int i = 0; i < Model.Count(); i++){
    <tr>
        <td>
           @(i + 1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.ElementAt(i).Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.ElementAt(i).CreatedOn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.ElementAt(i).ExpiresOn)
        </td>
        <td>
        </td>
    </tr>
}

</table>



<div>
    @Html.ActionLink("Back to Menu", "Menu")
</div>

AzureKeyVaultManager/AzureKeyVaultManager.Web/Views/KeyVault/Menu.cshtml
@{
    ViewBag.Title = "Menu";
}

<h2>Menu</h2>

<br/><br/>

<div>
    <p>@Html.ActionLink("List Secrets", "Secrets", "KeyVault") &raquo;</p>
   
    <p>@Html.ActionLink("Create Secret", "CreateSecret", "KeyVault") &raquo;</p>
   
    <p>@Html.ActionLink("List Keys", "Keys", "KeyVault") &raquo;</p>
</div>

AzureKeyVaultManager/AzureKeyVaultManager.Web/Views/KeyVault/SecretDetails.cshtml
@model IEnumerable<AzureKeyVaultManager.Web.Models.KeyVaultSecret>

@{
    ViewBag.Title = "SecretDetails";
}

<h3>Details</h3>
<br/>
<h4>@Model.First().SecretName has @Model.Count() version(s)</h4>

<table class="table">
    <tr>
        <th>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Version)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExpiresOn)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Version)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedOn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ExpiresOn)
        </td>
    </tr>
}

</table>

<div>
    @Html.ActionLink("Back to List", "Secrets")
</div>

AzureKeyVaultManager/AzureKeyVaultManager.Web/Views/KeyVault/Secrets.cshtml
@model IEnumerable<AzureKeyVaultManager.Web.Models.KeyVaultSecret>

@{
    ViewBag.Title = "Secrets";
}

<h3>Secrets</h3>
<h4>Vault : @Session["vaulturl"].ToString().ToLower() has @Model.Count() secret(s).</h4>

<p>
    @Html.ActionLink("Create New", "CreateSecret")
</p>

<p>
    Details : List all the versions of the secret.
    Delete : <strong> Will delete the secret and all its versions.</strong>
</p>

<table class="table">
    <tr>
        <th>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExpiresOn)
        </th>
        <th></th>
    </tr>


@for(int i = 0; i < Model.Count(); i++) {
    <tr>
        <td>
            @(i + 1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.ElementAt(i).Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.ElementAt(i).CreatedOn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.ElementAt(i).ExpiresOn)
        </td>
        <td>
            @Html.ActionLink("Details", "SecretDetails", new { secretName = Model.ElementAt(i).Name }) |
            @Html.ActionLink("Delete", "DeleteSecret", new { secretName = Model.ElementAt(i).Name })
        </td>
    </tr>
}

</table>


<div>
    @Html.ActionLink("Back to Menu", "Menu")
</div>

AzureKeyVaultManager/AzureKeyVaultManager.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Azure Key Vault Manager</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div id="fb-root"></div>
    <script>
        (function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Azure Key Vault Manager", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("New", "Index", "KeyVault")</li>
                    <li>@Html.ActionLink("Comments", "Index", "Comments")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - <a href="https://thuruinhttp.wordpress.com" target="_blank"> Thuru's Blog</a></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>